export const ROUTES = {
  dashboard: '/dashboard',
  planningDashboard: '/dashboard/demand-planning',
  customerServicesDashboard: '/dashboard/customer-services',
  ecommerceDashboard: '/dashboard/ecommerce',
  performanceDashboard: '/performance-dashboard',
  vehicleResearch: '/vehicle-research',
  vehicleProjects: '/vehicle-projects',
  productShapes: '/product-shapes',
  huntBoard: '/hunt-board',
  reworkComplaints: '/rework-complaints',
  samples: '/samples',
  uniqueVehicles: '/unique-vehicles',
  products: '/products',
  productRegistrations: '/product-registrations',
  vehicleOptions: '/vehicle-options',
  referenceData: '/reference-data',
  profileDefault: '/profiles/default',
  login: '/login',
} as const;
